In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
vehicles = pd.read_csv('../data/vehicle.csv')
emissions = pd.read_csv('../data/emissions.csv')
car_price = pd.read_csv('../data/vehicles.csv')

C:\Users\berat\AppData\Local\Temp\ipykernel_75328\382179092.py:1: DtypeWarning: Columns (72,74,75,77) have mixed types. Specify dtype option on import or set low_memory=False.
  vehicles = pd.read_csv('../data/vehicle.csv')

In [4]:
price = car_price.dropna(subset=['price','year','make','model','fuel','type','state','lat','long'])
price = price.reset_index(drop = True)
price

,price,year,make,model,fuel,type,state,lat,long
0,22590,2010.0,chevrolet,silverado 1500,gas,pickup,al,32.590000,-85.480000
1,15000,2013.0,ford,f-150 xlt,gas,truck,al,32.592000,-85.518900
2,27990,2012.0,gmc,sierra 2500 hd extended cab,gas,pickup,al,32.590000,-85.480000
3,2000,2015.0,chrysler,200,gas,sedan,ca,39.537052,-119.765434
4,2000,2016.0,chevrolet,impala lt,gas,sedan,ca,38.608256,-121.435199
...,...,...,...,...,...,...,...,...,...
312374,119900,2020.0,ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796
312376,34990,2020.0,cadillac,xt4 sport suv 4d,diesel,hatchback,wy,33.779214,-84.411811
312377,119991,2014.0,aston-martin,martin vanquish,gas,convertible,fl,27.946392,-82.342089
312378,119995,2021.0,chevrolet,corvette c8 z51,gas,convertible,az,34.630383,-112.405071

In [5]:
price = price[price['year'] >= 2014]
price = price[price['fuel'] == 'gas']
price

,price,year,make,model,fuel,type,state,lat,long
3,2000,2015.0,chrysler,200,gas,sedan,ca,39.537052,-119.765434
4,2000,2016.0,chevrolet,impala lt,gas,sedan,ca,38.608256,-121.435199
6,32990,2017.0,jeep,wrangler unlimited sport,gas,other,al,32.590000,-85.480000
7,2000,2018.0,ford,focus se,gas,sedan,ca,38.608256,-121.435199
12,2000,2014.0,chevrolet,camaro ss convertible,gas,convertible,ca,38.741256,-121.290465
...,...,...,...,...,...,...,...,...,...
312373,119900,2021.0,chevrolet,corvette c8,gas,convertible,nm,35.290749,-106.664200
312374,119900,2020.0,ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796
312377,119991,2014.0,aston-martin,martin vanquish,gas,convertible,fl,27.946392,-82.342089
312378,119995,2021.0,chevrolet,corvette c8 z51,gas,convertible,az,34.630383,-112.405071

In [6]:
price = price[price['make'].isin(['acura', 'audi', 'bmw', 'buick', 'cadillac', 'chevrolet', 'dodge', 'ford', 'gmc', 'honda', 'hyundai', 'infiniti', 'jeep', 'kia', 'lexus', 'lincoln', 'mazda', 'mercedes-benz', 'mitsubishi', 'nissan', 'ram', 'subaru', 'toyota', 'volkswagen', 'volvo'])]
price

,price,year,make,model,fuel,type,state,lat,long
4,2000,2016.0,chevrolet,impala lt,gas,sedan,ca,38.608256,-121.435199
6,32990,2017.0,jeep,wrangler unlimited sport,gas,other,al,32.590000,-85.480000
7,2000,2018.0,ford,focus se,gas,sedan,ca,38.608256,-121.435199
12,2000,2014.0,chevrolet,camaro ss convertible,gas,convertible,ca,38.741256,-121.290465
14,2000,2018.0,bmw,328i,gas,sedan,ct,41.382200,-72.858500
...,...,...,...,...,...,...,...,...,...
312372,30990,2018.0,mercedes-benz,glc 300 sport,gas,other,wy,33.779214,-84.411811
312373,119900,2021.0,chevrolet,corvette c8,gas,convertible,nm,35.290749,-106.664200
312374,119900,2020.0,ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796
312378,119995,2021.0,chevrolet,corvette c8 z51,gas,convertible,az,34.630383,-112.405071

In [7]:
price = price[price['price'] >= 5000]
price

,price,year,make,model,fuel,type,state,lat,long
6,32990,2017.0,jeep,wrangler unlimited sport,gas,other,al,32.590000,-85.480000
19,31590,2020.0,mazda,mx-5 miata club,gas,other,al,32.590000,-85.480000
23,16590,2016.0,jeep,renegade sport suv 4d,gas,other,al,32.590000,-85.480000
30,34990,2018.0,ford,mustang gt premium,gas,other,al,32.590000,-85.480000
46,33990,2020.0,jeep,wrangler sport suv 2d,gas,other,al,32.590000,-85.480000
...,...,...,...,...,...,...,...,...,...
312372,30990,2018.0,mercedes-benz,glc 300 sport,gas,other,wy,33.779214,-84.411811
312373,119900,2021.0,chevrolet,corvette c8,gas,convertible,nm,35.290749,-106.664200
312374,119900,2020.0,ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796
312378,119995,2021.0,chevrolet,corvette c8 z51,gas,convertible,az,34.630383,-112.405071

In [8]:
make_capitalized = {
    'acura': 'Acura',
    'audi': 'Audi',
    'bmw': 'BMW',
    'buick': 'Buick',
    'cadillac': 'Cadillac',
    'chevrolet': 'Chevrolet',
    'dodge': 'Dodge',
    'ford': 'Ford',
    'gmc': 'GMC',
    'honda': 'Honda',
    'hyundai': 'Hyundai',
    'infiniti': 'Infiniti',
    'jeep': 'Jeep',
    'kia': 'Kia',
    'lexus': 'Lexus',
    'lincoln': 'Lincoln',
    'mazda': 'Mazda',
    'mercedes-benz': 'Mercedes-Benz',
    'mitsubishi': 'Mitsubishi',
    'nissan': 'Nissan',
    'ram': 'Ram',
    'subaru': 'Subaru',
    'toyota': 'Toyota',
    'volkswagen': 'Volkswagen',
    'volvo': 'Volvo'
                    }

In [9]:
price['make'] = price['make'].replace(make_capitalized)
price

C:\Users\berat\AppData\Local\Temp\ipykernel_75328\3648298733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price['make'] = price['make'].replace(make_capitalized)

,price,year,make,model,fuel,type,state,lat,long
6,32990,2017.0,Jeep,wrangler unlimited sport,gas,other,al,32.590000,-85.480000
19,31590,2020.0,Mazda,mx-5 miata club,gas,other,al,32.590000,-85.480000
23,16590,2016.0,Jeep,renegade sport suv 4d,gas,other,al,32.590000,-85.480000
30,34990,2018.0,Ford,mustang gt premium,gas,other,al,32.590000,-85.480000
46,33990,2020.0,Jeep,wrangler sport suv 2d,gas,other,al,32.590000,-85.480000
...,...,...,...,...,...,...,...,...,...
312372,30990,2018.0,Mercedes-Benz,glc 300 sport,gas,other,wy,33.779214,-84.411811
312373,119900,2021.0,Chevrolet,corvette c8,gas,convertible,nm,35.290749,-106.664200
312374,119900,2020.0,Ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,Chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796
312378,119995,2021.0,Chevrolet,corvette c8 z51,gas,convertible,az,34.630383,-112.405071

In [10]:
price = price[~price['type'].isin(['other','bus','offroad','convertible'])]
price

,price,year,make,model,fuel,type,state,lat,long
1079,130000,2019.0,Chevrolet,corvette,gas,coupe,al,33.633900,-86.598100
1705,5000,2014.0,Ford,fiesta se,gas,sedan,ca,33.752400,-117.993900
1706,5000,2014.0,Honda,accord,gas,sedan,ca,38.583314,-121.314605
1712,5000,2014.0,Ford,focus se,gas,hatchback,co,38.244700,-104.531800
1721,5000,2016.0,Ford,explorer,gas,SUV,de,39.928564,-75.195883
...,...,...,...,...,...,...,...,...,...
312354,115990,2021.0,Ram,1500,gas,truck,mi,42.449125,-85.669529
312362,118000,2020.0,Chevrolet,corvette,gas,coupe,wa,46.567948,-120.485788
312371,119900,2020.0,Ford,mustang,gas,coupe,ma,42.475900,-73.377300
312374,119900,2020.0,Ford,mustang,gas,coupe,ny,42.475900,-73.377300
312375,119900,2021.0,Chevrolet,corvette,gas,coupe,wi,43.029559,-89.397796

In [11]:
type_rows_renamed = {
    'coupe': 'Midsize Sedans',
    'sedan': 'Midsize Sedans',
    'hatchback': 'Small Sedans',
    'SUV': 'SUVs',
    'wagon': 'Full-Size Sedans',
    'truck': 'Pickup Trucks',
    'mini-van': 'Vans',
    'van': 'Vans',
    'pickup': 'Pickup Trucks'
                    }

In [12]:
price['type'] = price['type'].replace(type_rows_renamed)
price = price.rename(columns = {'type' : 'VClass'})
price

C:\Users\berat\AppData\Local\Temp\ipykernel_75328\843515426.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price['type'] = price['type'].replace(type_rows_renamed)

,price,year,make,model,fuel,VClass,state,lat,long
1079,130000,2019.0,Chevrolet,corvette,gas,Midsize Sedans,al,33.633900,-86.598100
1705,5000,2014.0,Ford,fiesta se,gas,Midsize Sedans,ca,33.752400,-117.993900
1706,5000,2014.0,Honda,accord,gas,Midsize Sedans,ca,38.583314,-121.314605
1712,5000,2014.0,Ford,focus se,gas,Small Sedans,co,38.244700,-104.531800
1721,5000,2016.0,Ford,explorer,gas,SUVs,de,39.928564,-75.195883
...,...,...,...,...,...,...,...,...,...
312354,115990,2021.0,Ram,1500,gas,Pickup Trucks,mi,42.449125,-85.669529
312362,118000,2020.0,Chevrolet,corvette,gas,Midsize Sedans,wa,46.567948,-120.485788
312371,119900,2020.0,Ford,mustang,gas,Midsize Sedans,ma,42.475900,-73.377300
312374,119900,2020.0,Ford,mustang,gas,Midsize Sedans,ny,42.475900,-73.377300
312375,119900,2021.0,Chevrolet,corvette,gas,Midsize Sedans,wi,43.029559,-89.397796

In [13]:
price['state'].sort_values(ascending = True).unique()

array(['ak', 'al', 'ar', 'az', 'ca', 'co', 'ct', 'dc', 'de', 'fl', 'ga',
       'hi', 'ia', 'id', 'il', 'in', 'ks', 'ky', 'la', 'ma', 'md', 'me',
       'mi', 'mn', 'mo', 'ms', 'mt', 'nc', 'nd', 'ne', 'nh', 'nj', 'nm',
       'nv', 'ny', 'oh', 'ok', 'or', 'pa', 'ri', 'sc', 'sd', 'tn', 'tx',
       'ut', 'va', 'vt', 'wa', 'wi', 'wv', 'wy'], dtype=object)

In [14]:
state_full_name = {
    'ak': 'Alaska',
    'al': 'Alabama',
    'ar': 'Arkansas',
    'az': 'Arizona',
    'ca': 'California',
    'co': 'Colorado',
    'ct': 'Connecticut',
    'dc': 'District of Columbia (Washington, D.C.)',
    'de': 'Delaware',
    'fl': 'Florida',
    'ga': 'Georgia',
    'hi': 'Hawaii',
    'ia': 'Iowa',
    'id': 'Idaho',
    'il': 'Illinois',
    'in': 'Indiana',
    'ks': 'Kansas',
    'ky': 'Kentucky',
    'la': 'Louisiana',
    'ma': 'Massachusetts',
    'md': 'Maryland',
    'me': 'Maine',
    'mi': 'Michigan',
    'mn': 'Minnesota',
    'mo': 'Missouri',
    'ms': 'Mississippi',
    'mt': 'Montana',
    'nc': 'North Carolina',
    'nd': 'North Dakota',
    'ne': 'Nebraska',
    'nh': 'New Hampshire',
    'nj': 'New Jersey',
    'nm': 'New Mexico',
    'nv': 'Nevada',
    'ny': 'New York',
    'oh': 'Ohio',
    'ok': 'Oklahoma',
    'or': 'Oregon',
    'pa': 'Pennsylvania',
    'ri': 'Rhode Island',
    'sc': 'South Carolina',
    'sd': 'South Dakota',
    'tn': 'Tennessee',
    'tx': 'Texas',
    'ut': 'Utah',
    'va': 'Virginia',
    'vt': 'Vermont',
    'wa': 'Washington',
    'wi': 'Wisconsin',
    'wv': 'West Virginia',
    'wy': 'Wyoming'
                    }

In [15]:
price['state'] = price['state'].replace(state_full_name)
price

,price,year,make,model,fuel,VClass,state,lat,long
1079,130000,2019.0,Chevrolet,corvette,gas,Midsize Sedans,Alabama,33.633900,-86.598100
1705,5000,2014.0,Ford,fiesta se,gas,Midsize Sedans,California,33.752400,-117.993900
1706,5000,2014.0,Honda,accord,gas,Midsize Sedans,California,38.583314,-121.314605
1712,5000,2014.0,Ford,focus se,gas,Small Sedans,Colorado,38.244700,-104.531800
1721,5000,2016.0,Ford,explorer,gas,SUVs,Delaware,39.928564,-75.195883
...,...,...,...,...,...,...,...,...,...
312354,115990,2021.0,Ram,1500,gas,Pickup Trucks,Michigan,42.449125,-85.669529
312362,118000,2020.0,Chevrolet,corvette,gas,Midsize Sedans,Washington,46.567948,-120.485788
312371,119900,2020.0,Ford,mustang,gas,Midsize Sedans,Massachusetts,42.475900,-73.377300
312374,119900,2020.0,Ford,mustang,gas,Midsize Sedans,New York,42.475900,-73.377300
312375,119900,2021.0,Chevrolet,corvette,gas,Midsize Sedans,Wisconsin,43.029559,-89.397796

In [16]:
price = price.reset_index(drop = True)
price

,price,year,make,model,fuel,VClass,state,lat,long
0,130000,2019.0,Chevrolet,corvette,gas,Midsize Sedans,Alabama,33.633900,-86.598100
1,5000,2014.0,Ford,fiesta se,gas,Midsize Sedans,California,33.752400,-117.993900
2,5000,2014.0,Honda,accord,gas,Midsize Sedans,California,38.583314,-121.314605
3,5000,2014.0,Ford,focus se,gas,Small Sedans,Colorado,38.244700,-104.531800
4,5000,2016.0,Ford,explorer,gas,SUVs,Delaware,39.928564,-75.195883
...,...,...,...,...,...,...,...,...,...
101758,115990,2021.0,Ram,1500,gas,Pickup Trucks,Michigan,42.449125,-85.669529
101759,118000,2020.0,Chevrolet,corvette,gas,Midsize Sedans,Washington,46.567948,-120.485788
101760,119900,2020.0,Ford,mustang,gas,Midsize Sedans,Massachusetts,42.475900,-73.377300
101761,119900,2020.0,Ford,mustang,gas,Midsize Sedans,New York,42.475900,-73.377300
101762,119900,2021.0,Chevrolet,corvette,gas,Midsize Sedans,Wisconsin,43.029559,-89.397796

In [17]:
vehicles

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelCostA08,fuelType,fuelType1,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,make,model,mpgData,phevBlended,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,trany,UCity,UCityA,UHighway,UHighwayA,VClass,year,youSaveSpend,baseModel,guzzler,trans_dscr,tCharger,sCharger,atvType,fuelType2,rangeA,evMotor,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,14.167143,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,0,Regular,Regular Gasoline,-1,-1,25,0.0,0,0.0,0.0,0.0,0.0,0,0,1,0,0,Alfa Romeo,Spider Veloce 2000,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.3333,0.0,35.0000,0.0,Two Seaters,1985,-3250,Spider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
1,27.046364,0.0,0.0,0.0,9,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,0,Regular,Regular Gasoline,-1,-1,14,0.0,0,0.0,0.0,0.0,0.0,0,0,10,0,0,Ferrari,Testarossa,N,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,11.0000,0.0,19.0000,0.0,Two Seaters,1985,-15000,Testarossa,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
2,11.018889,0.0,0.0,0.0,23,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,329.148148,27,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,0,Regular,Regular Gasoline,-1,-1,33,0.0,0,0.0,0.0,0.0,0.0,19,77,100,0,0,Dodge,Charger,Y,False,0,0,0,0.0,0.0,0.0,0.0,Manual 5-spd,29.0000,0.0,47.0000,0.0,Subcompact Cars,1985,-500,Charger,NaN,SIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
3,27.046364,0.0,0.0,0.0,10,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,807.909091,11,0.0,0,0.0,0.0,0.0,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,0,Regular,Regular Gasoline,-1,-1,12,0.0,0,0.0,0.0,0.0,0.0,0,0,1000,0,0,Dodge,B150/B250 Wagon 2WD,N,False,0,0,0,0.0,0.0,0.0,0.0,Automatic 3-spd,12.2222,0.0,16.6667,0.0,Vans,1985,-15000,B150/B250 Wagon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
4,15.658421,0.0,0.0,0.0,17,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,467.736842,19,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,0,Premium,Premium Gasoline,-1,-1,23,0.0,0,0.0,0.0,0.0,0.0,0,0,10000,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,21.0000,0.0,32.0000,0.0,Compact Cars,1993,-8250,Legacy/Outback,NaN,NaN,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,13.523182,0.0,0.0,0.0,19,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,403.954545,22,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,0,Regular,Regular Gasoline,-1,-1,26,0.0,0,0.0,0.0,0.0,0.0,0,0,9995,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,24.0000,0.0,37.0000,0.0,Compact Cars,1993,-2750,Legacy/Outback,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
47519,12.935217,0.0,0.0,0.0,20,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,386.391304,23,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,0,Regular,Regular Gasoline,-1,-1,28,0.0,0,0.0,0.0,0.0,0.0,0,0,9996,0,14,Subaru,Legacy,N,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,25.0000,0.0,39.0000,0.0,Compact Cars,1993,-2250,Legacy/Outback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
47520,14.167143,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9997,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-3250,Legacy/Outback,NaN,CLKUP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
47521,14.167143,0.0,0.0,0.0,18,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,423.190476,21,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,0,Regular,Regular Gasoline,-1,-1,24,0.0,0,0.0,0.0,0.0,0.0,0,0,9998,0,14,Subaru,Legacy AWD,Y,False,0,90,0,0.0,0.0,0.0,0.0,Manual 5-spd,23.0000,0.0,34.0000,0.0,Compact Cars,1993,-3250,Legacy/Outback,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0
47522,16.528333,0.0,0.0,0.0,16,0.0,0,0.0,0.0,0.0,0.0,-1,-1,0.0,493.722222,18,0.0,0,0.0,0.0,0.0,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,0,Premium,Premium Gasoline,-1,-1,21,0.0,0,0.0,0.0,0.0,0.0,0,0,9999,0,14,Subaru,Legacy AWD Turbo,N,False,0,90,0,0.0,0.0,0.0,0.0,Automatic 4-spd,20.0000,0.0,29.0000,0.0,Compact Cars,1993,-9250,Legacy/Outback,NaN,CLKUP,T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,NaN,0,0,0

In [18]:
vehicles['range'].unique()

array([  0,  90,  88,  29,  38,  33,  95,  50,  65,  55, 105,  81,  70,
        72, 100,  73,  63,  62,  56,  94,  76, 265,  82,  68, 103, 208,
       122,  87,  75, 139,  84, 127,  93,  83, 242, 253, 270, 240, 257,
       250, 107, 234, 294,  59, 249, 259, 238, 187, 114, 210, 218, 315,
       200, 124, 289, 115, 125, 335,  89,  58, 111,  57, 310, 295, 151,
       258, 150, 153, 260, 239, 264, 226, 215, 204, 220, 370, 345, 325,
       285, 170, 330, 322, 304, 299, 373, 348, 326, 287, 328, 305, 272,
       201, 192, 110, 149, 203, 402, 291, 316, 233, 353, 371, 341, 300,
       303, 243, 351, 222, 387, 334, 211, 230, 199, 227, 225, 263, 244,
       212, 247, 405, 223, 314, 471, 451, 520, 481, 516, 469, 202, 181,
       185, 241, 232, 350, 256, 274, 358, 396, 333, 311, 340, 301, 282,
       324, 224, 277, 312, 279, 251, 245, 275, 320, 288, 248, 235, 262,
       246, 252, 228, 236, 271, 318, 296, 308, 217, 206, 216, 209, 255,
       446, 410, 384, 425, 321, 290, 174, 307, 361, 269, 276, 283, 278,
       317, 298, 450, 266, 297, 293, 254, 360, 196, 205, 267, 352, 207,
       191, 354, 380, 357, 393, 261, 280, 419, 394, 427, 231, 366, 313,
       319, 141, 273, 281, 485, 411, 382, 365, 339, 355, 400, 342, 359],
      dtype=int64)

In [19]:
vehicles.isna().sum().head(60)

barrels08              0
barrelsA08             0
charge120              0
charge240              0
city08                 0
city08U                0
cityA08                0
cityA08U               0
cityCD                 0
cityE                  0
cityUF                 0
co2                    0
co2A                   0
co2TailpipeAGpm        0
co2TailpipeGpm         0
comb08                 0
comb08U                0
combA08                0
combA08U               0
combE                  0
combinedCD             0
combinedUF             0
cylinders            801
displ                799
drive               1186
engId                  0
eng_dscr           17442
feScore                0
fuelCost08             0
fuelCostA08            0
fuelType               0
fuelType1              0
ghgScore               0
ghgScoreA              0
highway08              0
highway08U             0
highwayA08             0
highwayA08U            0
highwayCD              0
highwayE               0
highwayUF              0
hlv                    0
hpv                    0
id                     0
lv2                    0
lv4                    0
make                   0
model                  0
mpgData               41
phevBlended            0
pv2                    0
pv4                    0
range                  0
rangeCity              0
rangeCityA             0
rangeHwy               0
rangeHwyA              0
trany                 11
UCity                  0
UCityA                 0
dtype: int64

In [20]:
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47523 entries, 0 to 47522
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   barrels08        47523 non-null  float64
 1   barrelsA08       47523 non-null  float64
 2   charge120        47523 non-null  float64
 3   charge240        47523 non-null  float64
 4   city08           47523 non-null  int64
 5   city08U          47523 non-null  float64
 6   cityA08          47523 non-null  int64
 7   cityA08U         47523 non-null  float64
 8   cityCD           47523 non-null  float64
 9   cityE            47523 non-null  float64
 10  cityUF           47523 non-null  float64
 11  co2              47523 non-null  int64
 12  co2A             47523 non-null  int64
 13  co2TailpipeAGpm  47523 non-null  float64
 14  co2TailpipeGpm   47523 non-null  float64
 15  comb08           47523 non-null  int64
 16  comb08U          47523 non-null  float64
 17  combA08          47523 non-null  int64
 18  combA08U         47523 non-null  float64
 19  combE            47523 non-null  float64
 20  combinedCD       47523 non-null  float64
 21  combinedUF       47523 non-null  float64
 22  cylinders        46722 non-null  float64
 23  displ            46724 non-null  float64
 24  drive            46337 non-null  object
 25  engId            47523 non-null  int64
 26  eng_dscr         30081 non-null  object
 27  feScore          47523 non-null  int64
 28  fuelCost08       47523 non-null  int64
 29  fuelCostA08      47523 non-null  int64
 30  fuelType         47523 non-null  object
 31  fuelType1        47523 non-null  object
 32  ghgScore         47523 non-null  int64
 33  ghgScoreA        47523 non-null  int64
 34  highway08        47523 non-null  int64
 35  highway08U       47523 non-null  float64
 36  highwayA08       47523 non-null  int64
 37  highwayA08U      47523 non-null  float64
 38  highwayCD        47523 non-null  float64
 39  highwayE         47523 non-null  float64
 40  highwayUF        47523 non-null  float64
 41  hlv              47523 non-null  int64
 42  hpv              47523 non-null  int64
 43  id               47523 non-null  int64
 44  lv2              47523 non-null  int64
 45  lv4              47523 non-null  int64
 46  make             47523 non-null  object
 47  model            47523 non-null  object
 48  mpgData          47482 non-null  object
 49  phevBlended      47523 non-null  bool
 50  pv2              47523 non-null  int64
 51  pv4              47523 non-null  int64
 52  range            47523 non-null  int64
 53  rangeCity        47523 non-null  float64
 54  rangeCityA       47523 non-null  float64
 55  rangeHwy         47523 non-null  float64
 56  rangeHwyA        47523 non-null  float64
 57  trany            47512 non-null  object
 58  UCity            47523 non-null  float64
 59  UCityA           47523 non-null  float64
 60  UHighway         47523 non-null  float64
 61  UHighwayA        47523 non-null  float64
 62  VClass           47523 non-null  object
 63  year             47523 non-null  int64
 64  youSaveSpend     47523 non-null  int64
 65  baseModel        47523 non-null  object
 66  guzzler          2763 non-null   object
 67  trans_dscr       15044 non-null  object
 68  tCharger         10335 non-null  object
 69  sCharger         1006 non-null   object
 70  atvType          5321 non-null   object
 71  fuelType2        1896 non-null   object
 72  rangeA           1891 non-null   object
 73  evMotor          2437 non-null   object
 74  mfrCode          16715 non-null  object
 75  c240Dscr         141 non-null    object
 76  charge240b       47523 non-null  float64
 77  c240bDscr        135 non-null    object
 78  createdOn        47523 non-null  object
 79  modifiedOn       47523 non-null  object
 80  startStop        15834 non-null  object
 81  phevCity         47523 non-null  int64
 82  phevHwy          47523 non-null  int64
 83  phevComb         47523 non-null  int64
dtypes: bool(1), float64(32), int64(27), object(24)
memory usage: 30.1+ MB

In [21]:
vehicles.describe()

,barrels08,barrelsA08,charge120,charge240,city08,city08U,cityA08,cityA08U,cityCD,cityE,cityUF,co2,co2A,co2TailpipeAGpm,co2TailpipeGpm,comb08,comb08U,combA08,combA08U,combE,combinedCD,combinedUF,cylinders,displ,engId,feScore,fuelCost08,fuelCostA08,ghgScore,ghgScoreA,highway08,highway08U,highwayA08,highwayA08U,highwayCD,highwayE,highwayUF,hlv,hpv,id,lv2,lv4,pv2,pv4,range,rangeCity,rangeCityA,rangeHwy,rangeHwyA,UCity,UCityA,UHighway,UHighwayA,year,youSaveSpend,charge240b,phevCity,phevHwy,phevComb
count,47523.000000,47523.000000,47523.0,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.00000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,46722.000000,46724.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.00000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000,47523.000000
mean,15.173212,0.190030,0.0,0.178136,19.662079,8.940989,0.896303,0.770897,0.000501,0.981353,0.003658,125.518402,5.769291,16.18248,452.962060,21.829788,9.764593,0.945269,0.799961,1.002357,0.000393,0.003622,5.701575,3.272838,7107.122193,0.995329,2981.312207,115.731330,1.001284,-0.922164,25.601414,11.212158,1.035793,0.860892,0.000232,1.027378,0.003573,1.926015,9.739621,23925.738632,1.71881,5.908991,13.030385,32.978495,4.212318,1.632149,0.197188,1.517854,0.184759,25.073608,1.196986,35.997452,0.987824,2004.302401,-5385.355512,0.015435,0.311302,0.313553,0.310923
std,4.488236,0.976448,0.0,1.313176,11.914322,15.857898,6.821359,6.755519,0.036616,6.637931,0.044801,197.212236,56.718117,89.72145,133.224075,11.178347,16.063208,6.742997,6.639258,6.712149,0.031883,0.044296,1.772368,1.353612,16284.150148,3.085128,885.474882,635.147959,3.103706,0.654598,10.527150,17.006939,6.818559,6.656468,0.026479,6.821801,0.043643,5.870081,27.472945,13879.181757,4.24827,9.466032,30.565695,45.921929,34.297532,20.979617,2.881204,19.724843,2.611687,17.067712,9.648902,15.083867,6.637179,12.534077,4445.321813,0.321030,4.035418,3.894750,3.946077
min,0.047081,0.000000,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.00000,0.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,-1.000000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1984.000000,-38500.000000,0.000000,0.000000,0.000000,0.000000
25%,12.396250,0.000000,0.0,0.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.00000,373.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2.200000,0.000000,-1.000000,2400.000000,0.000000,-1.000000,-1.000000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11881.500000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.700000,0.000000,28.200000,0.000000,1993.000000,-8250.000000,0.000000,0.000000,0.000000,0.000000
50%,14.875500,0.000000,0.0,0.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,0.00000,444.350000,20.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,3.000000,164.000000,-1.000000,2950.000000,0.000000,-1.000000,-1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23919.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22.000000,0.000000,33.900000,0.000000,2005.000000,-5250.000000,0.000000,0.000000,0.000000,0.000000
75%,17.500588,0.000000,0.0,0.000000,21.000000,17.598600,0.000000,0.000000,0.000000,0.000000,0.000000,320.000000,-1.000000,0.00000,522.764706,24.000000,20.102400,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,4.200000,3833.000000,4.000000,3550.000000,0.000000,4.000000,-1.000000,28.000000,24.335350,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35980.500000,0.00000,13.000000,0.000000,91.000000,0.000000,0.000000,0.000000,0.000000,0.000000,26.666700,0.000000,40.000000,0.000000,2015.000000,-2500.000000,0.000000,0.000000,0.000000,0.000000
max,42.501429,16.528333,0.0,19.000000,153.000000,155.824200,145.000000,145.083500,5.350000,122.000000,0.927000,979.000000,713.000000,713.00000,1269.571429,142.000000,142.985100,133.000000,133.266200,121.000000,4.800000,0.920000,16.000000,8.400000,69102.000000,10.000000,9600.000000,4950.000000,10.000000,10.000000,140.000000,140.137600,121.000000,121.200500,4.060000,120.000000,0.910000,49.000000,195.000000,47965.000000,41.00000,55.000000,194.000000,192.000000,520.000000,520.800000,135.280000,520.500000,114.760000,224.800000,207.262200,187.100000,173.143600,2025.000000,9500.000000,9.600000,97.000000,81.000000,89.000000

In [22]:
vehicles.columns.value_counts()

barrels08    1
rangeCity    1
UHighwayA    1
UHighway     1
UCityA       1
            ..
eng_dscr     1
engId        1
drive        1
displ        1
phevComb     1
Name: count, Length: 84, dtype: int64

In [23]:
vehicles['VClass'].unique()

array(['Two Seaters', 'Subcompact Cars', 'Vans', 'Compact Cars',
       'Midsize Cars', 'Large Cars', 'Small Station Wagons',
       'Midsize-Large Station Wagons', 'Small Pickup Trucks',
       'Standard Pickup Trucks', 'Special Purpose Vehicle 2WD',
       'Special Purpose Vehicles', 'Minicompact Cars',
       'Special Purpose Vehicle 4WD', 'Midsize Station Wagons',
       'Small Pickup Trucks 2WD', 'Standard Pickup Trucks 2WD',
       'Standard Pickup Trucks 4WD', 'Vans, Cargo Type',
       'Vans, Passenger Type', 'Minivan - 2WD',
       'Sport Utility Vehicle - 4WD', 'Minivan - 4WD',
       'Sport Utility Vehicle - 2WD', 'Small Pickup Trucks 4WD',
       'Special Purpose Vehicle', 'Standard Pickup Trucks/2wd',
       'Vans Passenger', 'Special Purpose Vehicles/2wd',
       'Special Purpose Vehicles/4wd', 'Small Sport Utility Vehicle 4WD',
       'Standard Sport Utility Vehicle 2WD',
       'Standard Sport Utility Vehicle 4WD',
       'Small Sport Utility Vehicle 2WD'], dtype=object)

In [24]:
vehicles['baseModel'].value_counts()

baseModel
Sierra            733
F150              691
3 Series          571
911               567
Silverado         452
                 ...
Six Door            1
Windsor             1
24E                 1
85J                 1
Vantage Manual      1
Name: count, Length: 1451, dtype: int64

In [25]:
vehicles['year'].sort_values( ascending = True)

19373    1984
19015    1984
20083    1984
19016    1984
19017    1984
         ...
41533    2025
41534    2025
41535    2025
41501    2025
41741    2025
Name: year, Length: 47523, dtype: int64

In [26]:
vehicles.columns

Index(['barrels08', 'barrelsA08', 'charge120', 'charge240', 'city08',
       'city08U', 'cityA08', 'cityA08U', 'cityCD', 'cityE', 'cityUF', 'co2',
       'co2A', 'co2TailpipeAGpm', 'co2TailpipeGpm', 'comb08', 'comb08U',
       'combA08', 'combA08U', 'combE', 'combinedCD', 'combinedUF', 'cylinders',
       'displ', 'drive', 'engId', 'eng_dscr', 'feScore', 'fuelCost08',
       'fuelCostA08', 'fuelType', 'fuelType1', 'ghgScore', 'ghgScoreA',
       'highway08', 'highway08U', 'highwayA08', 'highwayA08U', 'highwayCD',
       'highwayE', 'highwayUF', 'hlv', 'hpv', 'id', 'lv2', 'lv4', 'make',
       'model', 'mpgData', 'phevBlended', 'pv2', 'pv4', 'range', 'rangeCity',
       'rangeCityA', 'rangeHwy', 'rangeHwyA', 'trany', 'UCity', 'UCityA',
       'UHighway', 'UHighwayA', 'VClass', 'year', 'youSaveSpend', 'baseModel',
       'guzzler', 'trans_dscr', 'tCharger', 'sCharger', 'atvType', 'fuelType2',
       'rangeA', 'evMotor', 'mfrCode', 'c240Dscr', 'charge240b', 'c240bDscr',
       'createdOn', 'modifiedOn', 'startStop', 'phevCity', 'phevHwy',
       'phevComb'],
      dtype='object')

In [27]:
required_columns = ['id','make','model','baseModel','year','createdOn','modifiedOn','youSaveSpend','barrels08','city08','co2','co2TailpipeGpm','comb08','comb08U','cylinders','displ','drive','engId','eng_dscr','feScore','fuelCost08','fuelType1','ghgScore','highway08','mfrCode','mpgData','trans_dscr','trany','UCity','UHighway','hlv','hpv','lv2','lv4','pv2','pv4','VClass','range']

In [28]:
vehicles = vehicles[required_columns]

In [29]:
print(vehicles.head())

      id        make                model        baseModel  year  \
0      1  Alfa Romeo   Spider Veloce 2000           Spider  1985
1     10     Ferrari           Testarossa       Testarossa  1985
2    100       Dodge              Charger          Charger  1985
3   1000       Dodge  B150/B250 Wagon 2WD  B150/B250 Wagon  1985
4  10000      Subaru     Legacy AWD Turbo   Legacy/Outback  1993

                      createdOn                    modifiedOn  youSaveSpend  \
0  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013         -3250
1  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013        -15000
2  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013          -500
3  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013        -15000
4  Tue Jan 01 00:00:00 EST 2013  Tue Jan 01 00:00:00 EST 2013         -8250

   barrels08  city08  co2  co2TailpipeGpm  comb08  comb08U  cylinders  displ  \
0  14.167143      19   -1      423.190476      21      0.0        4.0    2.0
1  27.046364       9   -1      807.909091      11      0.0       12.0    4.9
2  11.018889      23   -1      329.148148      27      0.0        4.0    2.2
3  27.046364      10   -1      807.909091      11      0.0        8.0    5.2
4  15.658421      17   -1      467.736842      19      0.0        4.0    2.2

                        drive  engId    eng_dscr  feScore  fuelCost08  \
0            Rear-Wheel Drive   9011       (FFS)       -1        2550
1            Rear-Wheel Drive  22020   (GUZZLER)       -1        4900
2           Front-Wheel Drive   2100       (FFS)       -1        2000
3            Rear-Wheel Drive   2850         NaN       -1        4900
4  4-Wheel or All-Wheel Drive  66031  (FFS,TRBO)       -1        3550

          fuelType1  ghgScore  highway08 mfrCode mpgData trans_dscr  \
0  Regular Gasoline        -1         25     NaN       Y        NaN
1  Regular Gasoline        -1         14     NaN       N        NaN
2  Regular Gasoline        -1         33     NaN       Y        SIL
3  Regular Gasoline        -1         12     NaN       N        NaN
4  Premium Gasoline        -1         23     NaN       N        NaN

             trany    UCity  UHighway  hlv  hpv  lv2  lv4  pv2  pv4  \
0     Manual 5-spd  23.3333   35.0000    0    0    0    0    0    0
1     Manual 5-spd  11.0000   19.0000    0    0    0    0    0    0
2     Manual 5-spd  29.0000   47.0000   19   77    0    0    0    0
3  Automatic 3-spd  12.2222   16.6667    0    0    0    0    0    0
4     Manual 5-spd  21.0000   32.0000    0    0    0   14    0   90

            VClass  range
0      Two Seaters      0
1      Two Seaters      0
2  Subcompact Cars      0
3             Vans      0
4     Compact Cars      0

In [30]:
vehicles

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range
0,1,Alfa Romeo,Spider Veloce 2000,Spider,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,19,-1,423.190476,21,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,Regular Gasoline,-1,25,NaN,Y,NaN,Manual 5-spd,23.3333,35.0000,0,0,0,0,0,0,Two Seaters,0
1,10,Ferrari,Testarossa,Testarossa,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,9,-1,807.909091,11,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,Regular Gasoline,-1,14,NaN,N,NaN,Manual 5-spd,11.0000,19.0000,0,0,0,0,0,0,Two Seaters,0
2,100,Dodge,Charger,Charger,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-500,11.018889,23,-1,329.148148,27,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,Regular Gasoline,-1,33,NaN,Y,SIL,Manual 5-spd,29.0000,47.0000,19,77,0,0,0,0,Subcompact Cars,0
3,1000,Dodge,B150/B250 Wagon 2WD,B150/B250 Wagon,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,10,-1,807.909091,11,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,Regular Gasoline,-1,12,NaN,N,NaN,Automatic 3-spd,12.2222,16.6667,0,0,0,0,0,0,Vans,0
4,10000,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-8250,15.658421,17,-1,467.736842,19,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,Premium Gasoline,-1,23,NaN,N,NaN,Manual 5-spd,21.0000,32.0000,0,0,0,14,0,90,Compact Cars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,9995,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2750,13.523182,19,-1,403.954545,22,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,Regular Gasoline,-1,26,NaN,N,CLKUP,Automatic 4-spd,24.0000,37.0000,0,0,0,14,0,90,Compact Cars,0
47519,9996,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2250,12.935217,20,-1,386.391304,23,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,Regular Gasoline,-1,28,NaN,N,NaN,Manual 5-spd,25.0000,39.0000,0,0,0,14,0,90,Compact Cars,0
47520,9997,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,CLKUP,Automatic 4-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47521,9998,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,NaN,Manual 5-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47522,9999,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-9250,16.528333,16,-1,493.722222,18,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,Premium Gasoline,-1,21,NaN,N,CLKUP,Automatic 4-spd,20.0000,29.0000,0,0,0,14,0,90,Compact Cars,0

In [31]:
vehicles['modifiedOn'].value_counts()

modifiedOn
Tue Jan 01 00:00:00 EST 2013    29169
Mon Sep 26 00:00:00 EDT 2016     6038
Wed Apr 05 00:00:00 EDT 2017      847
Thu Jan 18 00:00:00 EST 2024      370
Tue Jun 02 00:00:00 EDT 2020      358
                                ...
Mon Sep 14 00:00:00 EDT 2020        1
Fri Sep 24 00:00:00 EDT 2021        1
Fri Dec 16 00:00:00 EST 2016        1
Fri Feb 24 00:00:00 EST 2017        1
Fri Mar 21 00:00:00 EDT 2014        1
Name: count, Length: 298, dtype: int64

In [32]:
emissions

,efid,id,salesArea,score,scoreAlt,smartwayScore,standard,stdText
0,4HNXV03.2MJE,19332,3,1.0,-1.0,-1,B9,BIN 9
1,4HNXV03.2MJE,19332,7,1.0,-1.0,-1,L1,LEV
2,4HNXV03.2MJE,19333,3,1.0,-1.0,-1,B9,BIN 9
3,4HNXV03.2MJE,19333,7,1.0,-1.0,-1,L1,LEV
4,4ADXV01.8346,19334,3,1.0,-1.0,-1,B9,BIN 9
...,...,...,...,...,...,...,...,...
50182,PPRXV04.0PV8,47692,7,3.0,-1.0,-1,L3ULEV125,California LEV-III ULEV125
50183,PPRXV04.0PV8,47693,3,3.0,-1.0,-1,T3B125,Federal Tier 3 Bin 125
50184,PPRXV04.0PV8,47693,7,3.0,-1.0,-1,L3ULEV125,California LEV-III ULEV125
50185,PPRXT03.0CV6,47694,3,5.0,-1.0,-1,T3B70,Federal Tier 3 Bin 70
50186,PPRXT03.0CV6,47694,7,5.0,-1.0,-1,L3ULEV70,California LEV-III ULEV70

In [33]:
keep_columns = ['id','score']

In [34]:
emissions = emissions[keep_columns]
emissions

          id  score
0      19332    1.0
1      19332    1.0
2      19333    1.0
3      19333    1.0
4      19334    1.0
...      ...    ...
50182  47692    3.0
50183  47693    3.0
50184  47693    3.0
50185  47694    5.0
50186  47694    5.0

[50187 rows x 2 columns]

In [35]:
emissions.isna().sum()

id       0
score    0
dtype: int64

In [36]:
vehicles

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range
0,1,Alfa Romeo,Spider Veloce 2000,Spider,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,19,-1,423.190476,21,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,Regular Gasoline,-1,25,NaN,Y,NaN,Manual 5-spd,23.3333,35.0000,0,0,0,0,0,0,Two Seaters,0
1,10,Ferrari,Testarossa,Testarossa,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,9,-1,807.909091,11,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,Regular Gasoline,-1,14,NaN,N,NaN,Manual 5-spd,11.0000,19.0000,0,0,0,0,0,0,Two Seaters,0
2,100,Dodge,Charger,Charger,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-500,11.018889,23,-1,329.148148,27,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,Regular Gasoline,-1,33,NaN,Y,SIL,Manual 5-spd,29.0000,47.0000,19,77,0,0,0,0,Subcompact Cars,0
3,1000,Dodge,B150/B250 Wagon 2WD,B150/B250 Wagon,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,10,-1,807.909091,11,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,Regular Gasoline,-1,12,NaN,N,NaN,Automatic 3-spd,12.2222,16.6667,0,0,0,0,0,0,Vans,0
4,10000,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-8250,15.658421,17,-1,467.736842,19,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,Premium Gasoline,-1,23,NaN,N,NaN,Manual 5-spd,21.0000,32.0000,0,0,0,14,0,90,Compact Cars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,9995,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2750,13.523182,19,-1,403.954545,22,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,Regular Gasoline,-1,26,NaN,N,CLKUP,Automatic 4-spd,24.0000,37.0000,0,0,0,14,0,90,Compact Cars,0
47519,9996,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2250,12.935217,20,-1,386.391304,23,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,Regular Gasoline,-1,28,NaN,N,NaN,Manual 5-spd,25.0000,39.0000,0,0,0,14,0,90,Compact Cars,0
47520,9997,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,CLKUP,Automatic 4-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47521,9998,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,NaN,Manual 5-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47522,9999,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-9250,16.528333,16,-1,493.722222,18,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,Premium Gasoline,-1,21,NaN,N,CLKUP,Automatic 4-spd,20.0000,29.0000,0,0,0,14,0,90,Compact Cars,0

In [37]:
vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47523 entries, 0 to 47522
Data columns (total 38 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              47523 non-null  int64
 1   make            47523 non-null  object
 2   model           47523 non-null  object
 3   baseModel       47523 non-null  object
 4   year            47523 non-null  int64
 5   createdOn       47523 non-null  object
 6   modifiedOn      47523 non-null  object
 7   youSaveSpend    47523 non-null  int64
 8   barrels08       47523 non-null  float64
 9   city08          47523 non-null  int64
 10  co2             47523 non-null  int64
 11  co2TailpipeGpm  47523 non-null  float64
 12  comb08          47523 non-null  int64
 13  comb08U         47523 non-null  float64
 14  cylinders       46722 non-null  float64
 15  displ           46724 non-null  float64
 16  drive           46337 non-null  object
 17  engId           47523 non-null  int64
 18  eng_dscr        30081 non-null  object
 19  feScore         47523 non-null  int64
 20  fuelCost08      47523 non-null  int64
 21  fuelType1       47523 non-null  object
 22  ghgScore        47523 non-null  int64
 23  highway08       47523 non-null  int64
 24  mfrCode         16715 non-null  object
 25  mpgData         47482 non-null  object
 26  trans_dscr      15044 non-null  object
 27  trany           47512 non-null  object
 28  UCity           47523 non-null  float64
 29  UHighway        47523 non-null  float64
 30  hlv             47523 non-null  int64
 31  hpv             47523 non-null  int64
 32  lv2             47523 non-null  int64
 33  lv4             47523 non-null  int64
 34  pv2             47523 non-null  int64
 35  pv4             47523 non-null  int64
 36  VClass          47523 non-null  object
 37  range           47523 non-null  int64
dtypes: float64(7), int64(18), object(13)
memory usage: 13.8+ MB

In [38]:
vehicles = vehicles.drop_duplicates(subset = 'id', keep = 'last')
vehicles

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range
0,1,Alfa Romeo,Spider Veloce 2000,Spider,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,19,-1,423.190476,21,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,Regular Gasoline,-1,25,NaN,Y,NaN,Manual 5-spd,23.3333,35.0000,0,0,0,0,0,0,Two Seaters,0
1,10,Ferrari,Testarossa,Testarossa,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,9,-1,807.909091,11,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,Regular Gasoline,-1,14,NaN,N,NaN,Manual 5-spd,11.0000,19.0000,0,0,0,0,0,0,Two Seaters,0
2,100,Dodge,Charger,Charger,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-500,11.018889,23,-1,329.148148,27,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,Regular Gasoline,-1,33,NaN,Y,SIL,Manual 5-spd,29.0000,47.0000,19,77,0,0,0,0,Subcompact Cars,0
3,1000,Dodge,B150/B250 Wagon 2WD,B150/B250 Wagon,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,10,-1,807.909091,11,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,Regular Gasoline,-1,12,NaN,N,NaN,Automatic 3-spd,12.2222,16.6667,0,0,0,0,0,0,Vans,0
4,10000,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-8250,15.658421,17,-1,467.736842,19,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,Premium Gasoline,-1,23,NaN,N,NaN,Manual 5-spd,21.0000,32.0000,0,0,0,14,0,90,Compact Cars,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,9995,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2750,13.523182,19,-1,403.954545,22,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,Regular Gasoline,-1,26,NaN,N,CLKUP,Automatic 4-spd,24.0000,37.0000,0,0,0,14,0,90,Compact Cars,0
47519,9996,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2250,12.935217,20,-1,386.391304,23,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,Regular Gasoline,-1,28,NaN,N,NaN,Manual 5-spd,25.0000,39.0000,0,0,0,14,0,90,Compact Cars,0
47520,9997,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,CLKUP,Automatic 4-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47521,9998,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,NaN,Manual 5-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0
47522,9999,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-9250,16.528333,16,-1,493.722222,18,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,Premium Gasoline,-1,21,NaN,N,CLKUP,Automatic 4-spd,20.0000,29.0000,0,0,0,14,0,90,Compact Cars,0

In [39]:
emissions

          id  score
0      19332    1.0
1      19332    1.0
2      19333    1.0
3      19333    1.0
4      19334    1.0
...      ...    ...
50182  47692    3.0
50183  47693    3.0
50184  47693    3.0
50185  47694    5.0
50186  47694    5.0

[50187 rows x 2 columns]

In [40]:
emissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50187 entries, 0 to 50186
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50187 non-null  int64
 1   score   50187 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 784.3 KB

In [41]:
emissions = emissions.drop_duplicates(subset = 'id', keep = 'last')
emissions

          id  score
1      19332    1.0
3      19333    1.0
5      19334    1.0
7      19335    1.0
9      19336    1.0
...      ...    ...
50178  47690    7.0
50180  47691    7.0
50182  47692    3.0
50184  47693    3.0
50186  47694    5.0

[24579 rows x 2 columns]

In [42]:
cars = pd.merge(vehicles, emissions, on = 'id', how = 'left')
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score
0,1,Alfa Romeo,Spider Veloce 2000,Spider,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,19,-1,423.190476,21,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,Regular Gasoline,-1,25,NaN,Y,NaN,Manual 5-spd,23.3333,35.0000,0,0,0,0,0,0,Two Seaters,0,NaN
1,10,Ferrari,Testarossa,Testarossa,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,9,-1,807.909091,11,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,Regular Gasoline,-1,14,NaN,N,NaN,Manual 5-spd,11.0000,19.0000,0,0,0,0,0,0,Two Seaters,0,NaN
2,100,Dodge,Charger,Charger,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-500,11.018889,23,-1,329.148148,27,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,Regular Gasoline,-1,33,NaN,Y,SIL,Manual 5-spd,29.0000,47.0000,19,77,0,0,0,0,Subcompact Cars,0,NaN
3,1000,Dodge,B150/B250 Wagon 2WD,B150/B250 Wagon,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,10,-1,807.909091,11,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,Regular Gasoline,-1,12,NaN,N,NaN,Automatic 3-spd,12.2222,16.6667,0,0,0,0,0,0,Vans,0,NaN
4,10000,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-8250,15.658421,17,-1,467.736842,19,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,Premium Gasoline,-1,23,NaN,N,NaN,Manual 5-spd,21.0000,32.0000,0,0,0,14,0,90,Compact Cars,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,9995,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2750,13.523182,19,-1,403.954545,22,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,Regular Gasoline,-1,26,NaN,N,CLKUP,Automatic 4-spd,24.0000,37.0000,0,0,0,14,0,90,Compact Cars,0,NaN
47519,9996,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2250,12.935217,20,-1,386.391304,23,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,Regular Gasoline,-1,28,NaN,N,NaN,Manual 5-spd,25.0000,39.0000,0,0,0,14,0,90,Compact Cars,0,NaN
47520,9997,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,CLKUP,Automatic 4-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0,NaN
47521,9998,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,NaN,Manual 5-spd,23.0000,34.0000,0,0,0,14,0,90,Compact Cars,0,NaN
47522,9999,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-9250,16.528333,16,-1,493.722222,18,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,Premium Gasoline,-1,21,NaN,N,CLKUP,Automatic 4-spd,20.0000,29.0000,0,0,0,14,0,90,Compact Cars,0,NaN

In [43]:
VClass_simplified = {
    'Minivan - 2WD': 'Vans',
    'Minivan - 4WD': 'Vans',
    'Small Pickup Trucks 2WD': 'Pickup Trucks',
    'Small Pickup Trucks 4WD': 'Pickup Trucks',
    'Small Sport Utility Vehicle 2WD': 'SUVs',
    'Small Sport Utility Vehicle 4WD': 'SUVs',
    'Standard Pickup Trucks 2WD': 'Pickup Trucks',
    'Standard Pickup Trucks 4WD': 'Pickup Trucks',
    'Standard Sport Utility Vehicle 2WD': 'SUVs',
    'Standard Sport Utility Vehicle 4WD': 'SUVs',
    'Vans, Cargo Type': 'Vans',
    'Vans, Passenger Type': 'Vans',
    'Special Purpose Vehicle 2WD': 'Special Purpose Vehicle',
    'Special Purpose Vehicle 4WD': 'Special Purpose Vehicle',
    'Compact Cars': 'Midsize Sedans',
    'Subcompact Cars': 'Small Sedans',
    'Midsize Cars': 'Midsize Sedans',
    'Large Cars': 'Full-Size Sedans',
    'Minicompact Cars': 'Small Sedans',
    'Two Seaters': 'Small Sedans',
    'Midsize Station Wagons': 'Full-Size Sedans',
    'Small Station Wagons': 'Full-Size Sedans'
                    }

In [44]:
cars['VClass'] = cars['VClass'].replace(VClass_simplified)

In [45]:
cars = cars[cars['VClass'] != 'Special Purpose Vehicle']
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score
0,1,Alfa Romeo,Spider Veloce 2000,Spider,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,19,-1,423.190476,21,0.0,4.0,2.0,Rear-Wheel Drive,9011,(FFS),-1,2550,Regular Gasoline,-1,25,NaN,Y,NaN,Manual 5-spd,23.3333,35.0000,0,0,0,0,0,0,Small Sedans,0,NaN
1,10,Ferrari,Testarossa,Testarossa,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,9,-1,807.909091,11,0.0,12.0,4.9,Rear-Wheel Drive,22020,(GUZZLER),-1,4900,Regular Gasoline,-1,14,NaN,N,NaN,Manual 5-spd,11.0000,19.0000,0,0,0,0,0,0,Small Sedans,0,NaN
2,100,Dodge,Charger,Charger,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-500,11.018889,23,-1,329.148148,27,0.0,4.0,2.2,Front-Wheel Drive,2100,(FFS),-1,2000,Regular Gasoline,-1,33,NaN,Y,SIL,Manual 5-spd,29.0000,47.0000,19,77,0,0,0,0,Small Sedans,0,NaN
3,1000,Dodge,B150/B250 Wagon 2WD,B150/B250 Wagon,1985,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-15000,27.046364,10,-1,807.909091,11,0.0,8.0,5.2,Rear-Wheel Drive,2850,NaN,-1,4900,Regular Gasoline,-1,12,NaN,N,NaN,Automatic 3-spd,12.2222,16.6667,0,0,0,0,0,0,Vans,0,NaN
4,10000,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-8250,15.658421,17,-1,467.736842,19,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3550,Premium Gasoline,-1,23,NaN,N,NaN,Manual 5-spd,21.0000,32.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47518,9995,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2750,13.523182,19,-1,403.954545,22,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2450,Regular Gasoline,-1,26,NaN,N,CLKUP,Automatic 4-spd,24.0000,37.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN
47519,9996,Subaru,Legacy,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-2250,12.935217,20,-1,386.391304,23,0.0,4.0,2.2,Front-Wheel Drive,66030,(FFS),-1,2350,Regular Gasoline,-1,28,NaN,N,NaN,Manual 5-spd,25.0000,39.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN
47520,9997,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,CLKUP,Automatic 4-spd,23.0000,34.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN
47521,9998,Subaru,Legacy AWD,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-3250,14.167143,18,-1,423.190476,21,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66030,(FFS),-1,2550,Regular Gasoline,-1,24,NaN,Y,NaN,Manual 5-spd,23.0000,34.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN
47522,9999,Subaru,Legacy AWD Turbo,Legacy/Outback,1993,Tue Jan 01 00:00:00 EST 2013,Tue Jan 01 00:00:00 EST 2013,-9250,16.528333,16,-1,493.722222,18,0.0,4.0,2.2,4-Wheel or All-Wheel Drive,66031,"(FFS,TRBO)",-1,3750,Premium Gasoline,-1,21,NaN,N,CLKUP,Automatic 4-spd,20.0000,29.0000,0,0,0,14,0,90,Midsize Sedans,0,NaN

In [46]:
cars = cars[(cars['year'] >= 2014) & (cars['year'] < 2024)]
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score
25696,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0
25699,33400,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,500,9.917000,26,295,295.0,30,30.0228,4.0,2.5,Front-Wheel Drive,7,SIDI,8,1800,Regular Gasoline,8,37,TKX,Y,NaN,Automatic (S6),33.9088,53.9111,0,0,0,15,0,100,Midsize Sedans,0,9.0
25700,33401,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,-500,11.018889,25,328,328.0,27,27.0631,4.0,2.5,Front-Wheel Drive,1,SIDI,7,2000,Regular Gasoline,7,31,TKX,Y,NaN,Automatic (S6),31.5991,44.5607,0,0,0,0,0,0,SUVs,0,6.0
25701,33402,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,26,306,306.0,29,28.9587,4.0,2.0,Front-Wheel Drive,3,SIDI,7,1850,Regular Gasoline,7,34,TKX,Y,NaN,Manual 6-spd,33.7000,48.9000,0,0,0,0,0,0,SUVs,0,6.0
25702,33403,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,0,10.625357,26,311,311.0,28,28.4304,4.0,2.0,Front-Wheel Drive,4,SIDI,7,1900,Regular Gasoline,7,32,TKX,N,NaN,Automatic (S6),34.1482,45.4998,0,0,0,0,0,0,SUVs,0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41279,47547,Toyota,Mirai Limited,Mirai,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.742585,67,0,0.0,65,65.4566,NaN,NaN,Rear-Wheel Drive,203,PEFC,10,0,Hydrogen,10,64,TYX,N,NaN,Automatic (variable gear ratios),95.6017,91.0732,0,0,0,10,0,93,Midsize Sedans,357,10.0
41280,47548,Toyota,Mirai XLE,Mirai,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.954800,76,0,0.0,74,74.0843,NaN,NaN,Rear-Wheel Drive,202,PEFC,10,0,Hydrogen,10,71,TYX,N,NaN,Automatic (variable gear ratios),109.1000,102.1000,0,0,0,10,0,93,Midsize Sedans,402,10.0
41440,47692,Porsche,Panamera Turbo S Executive,Panamera,2023,Wed Feb 21 00:00:00 EST 2024,Tue Apr 16 00:00:00 EDT 2024,-10250,17.500588,15,525,525.0,17,17.0000,8.0,4.0,All-Wheel Drive,651,SIDI,3,3950,Premium Gasoline,3,21,PRX,N,NaN,Automatic (AM-S8),19.0000,29.9000,27,101,0,0,0,0,Full-Size Sedans,0,3.0
41441,47693,Porsche,Panamera Turbo S ST,Panamera,2023,Wed Feb 21 00:00:00 EST 2024,Tue Apr 16 00:00:00 EDT 2024,-10250,17.500588,15,525,525.0,17,17.0000,8.0,4.0,All-Wheel Drive,652,SIDI,3,3950,Premium Gasoline,3,21,PRX,N,NaN,Automatic (AM-S8),19.0000,29.9000,0,0,0,25,0,99,Full-Size Sedans,0,3.0
41442,47694,Porsche,Cayenne Coupe,Cayenne,2023,Wed Feb 21 00:00:00 EST 2024,Tue Apr 16 00:00:00 EDT 2024,-8250,15.658421,17,466,466.0,19,19.0000,6.0,3.0,All-Wheel Drive,402,SIDI,4,3550,Premium Gasoline,4,22,PRX,N,NaN,Automatic (S8),22.0000,31.5000,0,0,0,0,0,0,SUVs,0,5.0

In [47]:
makes_needed = ['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Dodge', 'Ford', 'GMC', 'Honda', 'Hyundai', 'Infiniti', 'Jeep', 'Kia', 'Lexus', 'Lincoln', 'Mazda', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Ram', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo']

In [48]:
cars = cars[cars['make'].isin(makes_needed)]
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score
25696,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0
25699,33400,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,500,9.917000,26,295,295.0,30,30.0228,4.0,2.5,Front-Wheel Drive,7,SIDI,8,1800,Regular Gasoline,8,37,TKX,Y,NaN,Automatic (S6),33.9088,53.9111,0,0,0,15,0,100,Midsize Sedans,0,9.0
25700,33401,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,-500,11.018889,25,328,328.0,27,27.0631,4.0,2.5,Front-Wheel Drive,1,SIDI,7,2000,Regular Gasoline,7,31,TKX,Y,NaN,Automatic (S6),31.5991,44.5607,0,0,0,0,0,0,SUVs,0,6.0
25701,33402,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,26,306,306.0,29,28.9587,4.0,2.0,Front-Wheel Drive,3,SIDI,7,1850,Regular Gasoline,7,34,TKX,Y,NaN,Manual 6-spd,33.7000,48.9000,0,0,0,0,0,0,SUVs,0,6.0
25702,33403,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,0,10.625357,26,311,311.0,28,28.4304,4.0,2.0,Front-Wheel Drive,4,SIDI,7,1900,Regular Gasoline,7,32,TKX,N,NaN,Automatic (S6),34.1482,45.4998,0,0,0,0,0,0,SUVs,0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41276,47544,Hyundai,Nexo,Nexo,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.520400,59,0,0.0,57,57.0000,NaN,NaN,Front-Wheel Drive,57,PEM,9,0,Hydrogen,10,54,HYX,N,NaN,Automatic (A1),86.3940,78.4380,30,101,0,0,0,0,SUVs,354,10.0
41277,47545,Hyundai,Nexo Blue,Nexo,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.629000,65,0,0.0,61,61.0000,NaN,NaN,Front-Wheel Drive,58,PEM,10,0,Hydrogen,10,58,HYX,N,NaN,Automatic (A1),95.3700,84.2520,30,101,0,0,0,0,SUVs,380,10.0
41278,47546,Toyota,Mirai LE,Mirai,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.954800,76,0,0.0,74,74.0843,NaN,NaN,Rear-Wheel Drive,201,PEFC,10,0,Hydrogen,10,71,TYX,N,NaN,Automatic (variable gear ratios),109.1000,102.1000,0,0,0,10,0,93,Midsize Sedans,330,10.0
41279,47547,Toyota,Mirai Limited,Mirai,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.742585,67,0,0.0,65,65.4566,NaN,NaN,Rear-Wheel Drive,203,PEFC,10,0,Hydrogen,10,64,TYX,N,NaN,Automatic (variable gear ratios),95.6017,91.0732,0,0,0,10,0,93,Midsize Sedans,357,10.0
41280,47548,Toyota,Mirai XLE,Mirai,2022,Thu Mar 31 00:00:00 EDT 2022,Thu Mar 31 00:00:00 EDT 2022,9500,1.954800,76,0,0.0,74,74.0843,NaN,NaN,Rear-Wheel Drive,202,PEFC,10,0,Hydrogen,10,71,TYX,N,NaN,Automatic (variable gear ratios),109.1000,102.1000,0,0,0,10,0,93,Midsize Sedans,402,10.0

In [49]:
print(cars['fuelType1'].unique())

['Regular Gasoline' 'Premium Gasoline' 'Diesel' 'Midgrade Gasoline'
 'Electricity' 'Natural Gas' 'Hydrogen']

In [50]:
cars = cars[cars['fuelType1'].isin(['Regular Gasoline', 'Premium Gasoline', 'Midgrade Gasoline'])]
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score
25696,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0
25699,33400,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,500,9.917000,26,295,295.0,30,30.0228,4.0,2.5,Front-Wheel Drive,7,SIDI,8,1800,Regular Gasoline,8,37,TKX,Y,NaN,Automatic (S6),33.9088,53.9111,0,0,0,15,0,100,Midsize Sedans,0,9.0
25700,33401,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,-500,11.018889,25,328,328.0,27,27.0631,4.0,2.5,Front-Wheel Drive,1,SIDI,7,2000,Regular Gasoline,7,31,TKX,Y,NaN,Automatic (S6),31.5991,44.5607,0,0,0,0,0,0,SUVs,0,6.0
25701,33402,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,26,306,306.0,29,28.9587,4.0,2.0,Front-Wheel Drive,3,SIDI,7,1850,Regular Gasoline,7,34,TKX,Y,NaN,Manual 6-spd,33.7000,48.9000,0,0,0,0,0,0,SUVs,0,6.0
25702,33403,Mazda,CX-5 2WD,CX-5,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,0,10.625357,26,311,311.0,28,28.4304,4.0,2.0,Front-Wheel Drive,4,SIDI,7,1900,Regular Gasoline,7,32,TKX,N,NaN,Automatic (S6),34.1482,45.4998,0,0,0,0,0,0,SUVs,0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41244,47515,GMC,Canyon AT4X 4WD,Canyon,2023,Mon Nov 06 00:00:00 EST 2023,Wed Feb 21 00:00:00 EST 2024,-7250,18.594375,16,539,539.0,16,16.4169,4.0,2.7,4-Wheel Drive,904,SIDI,3,3350,Regular Gasoline,3,16,GMX,N,NaN,Automatic 8-spd,20.4000,27.3000,0,0,0,0,0,0,Pickup Trucks,0,7.0
41245,47516,Mercedes-Benz,GLC300,GLC-Class,2023,Mon Nov 06 00:00:00 EST 2023,Thu Jan 18 00:00:00 EST 2024,-2500,10.625357,25,316,316.0,28,27.9274,4.0,2.0,Rear-Wheel Drive,111,SIDI; Mild Hybrid,6,2400,Premium Gasoline,6,32,MBX,N,NaN,Automatic 9-spd,32.7000,46.2000,0,0,0,0,0,0,SUVs,0,7.0
41246,47517,Mitsubishi,Outlander Sport 2WD,Outlander,2023,Mon Nov 06 00:00:00 EST 2023,Mon Nov 06 00:00:00 EST 2023,-1250,11.900400,23,354,354.0,25,25.0000,4.0,2.4,Front-Wheel Drive,225,NaN,5,2150,Regular Gasoline,5,29,MTX,N,NaN,Automatic (AV-S6),30.2981,41.2850,0,0,0,0,0,0,SUVs,0,5.0
41247,47518,Mercedes-Benz,GLC300 4matic,GLC-Class,2023,Mon Nov 06 00:00:00 EST 2023,Thu Jan 18 00:00:00 EST 2024,-3500,11.442692,23,338,338.0,26,26.0877,4.0,2.0,All-Wheel Drive,112,SIDI; Mild Hybrid,5,2600,Premium Gasoline,5,31,MBX,N,NaN,Automatic 9-spd,29.6000,44.5000,0,0,0,0,0,0,SUVs,0,7.0
41248,47519,Toyota,Corolla Cross Hybrid AWD,Corolla Cross,2023,Mon Nov 06 00:00:00 EST 2023,Tue Apr 30 00:00:00 EDT 2024,3000,7.083571,45,209,209.0,42,42.0000,4.0,2.0,All-Wheel Drive,82,SIDI & PFI; Hybrid,8,1300,Regular Gasoline,8,38,TYX,Y,NaN,Automatic (AV-S6),66.7500,57.6664,0,0,0,0,0,0,SUVs,0,7.0

In [51]:
price

,price,year,make,model,fuel,VClass,state,lat,long
0,130000,2019.0,Chevrolet,corvette,gas,Midsize Sedans,Alabama,33.633900,-86.598100
1,5000,2014.0,Ford,fiesta se,gas,Midsize Sedans,California,33.752400,-117.993900
2,5000,2014.0,Honda,accord,gas,Midsize Sedans,California,38.583314,-121.314605
3,5000,2014.0,Ford,focus se,gas,Small Sedans,Colorado,38.244700,-104.531800
4,5000,2016.0,Ford,explorer,gas,SUVs,Delaware,39.928564,-75.195883
...,...,...,...,...,...,...,...,...,...
101758,115990,2021.0,Ram,1500,gas,Pickup Trucks,Michigan,42.449125,-85.669529
101759,118000,2020.0,Chevrolet,corvette,gas,Midsize Sedans,Washington,46.567948,-120.485788
101760,119900,2020.0,Ford,mustang,gas,Midsize Sedans,Massachusetts,42.475900,-73.377300
101761,119900,2020.0,Ford,mustang,gas,Midsize Sedans,New York,42.475900,-73.377300
101762,119900,2021.0,Chevrolet,corvette,gas,Midsize Sedans,Wisconsin,43.029559,-89.397796

In [52]:
# cars = pd.merge(cars, price, on = ['make', 'year','VClass'], how = 'left')
# cars

In [53]:
print(price['price'].dtype)

int64

In [54]:
price = price.groupby(['make', 'year', 'VClass', 'lat', 'long', 'state']).agg(avg_price = ('price', 'mean')).reset_index()
price

,make,year,VClass,lat,long,state,avg_price
0,Acura,2014.0,Full-Size Sedans,43.109500,-88.486200,Wisconsin,16480.000000
1,Acura,2014.0,Midsize Sedans,25.753900,-80.225300,Florida,11495.000000
2,Acura,2014.0,Midsize Sedans,25.986242,-80.163834,Florida,11999.000000
3,Acura,2014.0,Midsize Sedans,27.588500,-80.392300,Florida,14852.000000
4,Acura,2014.0,Midsize Sedans,27.999033,-82.459702,Florida,14995.000000
...,...,...,...,...,...,...,...
63139,Volvo,2021.0,SUVs,35.283445,-120.658029,California,64557.315789
63140,Volvo,2021.0,SUVs,35.283445,-120.658029,Colorado,68998.000000
63141,Volvo,2021.0,SUVs,35.283445,-120.658029,Texas,68998.000000
63142,Volvo,2021.0,SUVs,44.052780,-123.128308,Oregon,61999.000000
63143,Volvo,2021.0,SUVs,61.217832,-149.870253,Alaska,54995.000000

In [55]:
cars = pd.merge(cars, price, on = ['make', 'year', 'VClass'], how = 'left')
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score,lat,long,state,avg_price
0,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.080000,-80.440000,Florida,15990.0
1,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.770000,-80.200000,Florida,15990.0
2,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,27.588500,-80.392300,Florida,13900.0
3,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.549966,-81.391525,Florida,6500.0
4,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.610096,-81.298342,Florida,12900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944378,47515,GMC,Canyon AT4X 4WD,Canyon,2023,Mon Nov 06 00:00:00 EST 2023,Wed Feb 21 00:00:00 EST 2024,-7250,18.594375,16,539,539.0,16,16.4169,4.0,2.7,4-Wheel Drive,904,SIDI,3,3350,Regular Gasoline,3,16,GMX,N,NaN,Automatic 8-spd,20.4000,27.3000,0,0,0,0,0,0,Pickup Trucks,0,7.0,NaN,NaN,NaN,NaN
944379,47516,Mercedes-Benz,GLC300,GLC-Class,2023,Mon Nov 06 00:00:00 EST 2023,Thu Jan 18 00:00:00 EST 2024,-2500,10.625357,25,316,316.0,28,27.9274,4.0,2.0,Rear-Wheel Drive,111,SIDI; Mild Hybrid,6,2400,Premium Gasoline,6,32,MBX,N,NaN,Automatic 9-spd,32.7000,46.2000,0,0,0,0,0,0,SUVs,0,7.0,NaN,NaN,NaN,NaN
944380,47517,Mitsubishi,Outlander Sport 2WD,Outlander,2023,Mon Nov 06 00:00:00 EST 2023,Mon Nov 06 00:00:00 EST 2023,-1250,11.900400,23,354,354.0,25,25.0000,4.0,2.4,Front-Wheel Drive,225,NaN,5,2150,Regular Gasoline,5,29,MTX,N,NaN,Automatic (AV-S6),30.2981,41.2850,0,0,0,0,0,0,SUVs,0,5.0,NaN,NaN,NaN,NaN
944381,47518,Mercedes-Benz,GLC300 4matic,GLC-Class,2023,Mon Nov 06 00:00:00 EST 2023,Thu Jan 18 00:00:00 EST 2024,-3500,11.442692,23,338,338.0,26,26.0877,4.0,2.0,All-Wheel Drive,112,SIDI; Mild Hybrid,5,2600,Premium Gasoline,5,31,MBX,N,NaN,Automatic 9-spd,29.6000,44.5000,0,0,0,0,0,0,SUVs,0,7.0,NaN,NaN,NaN,NaN
944382,47519,Toyota,Corolla Cross Hybrid AWD,Corolla Cross,2023,Mon Nov 06 00:00:00 EST 2023,Tue Apr 30 00:00:00 EDT 2024,3000,7.083571,45,209,209.0,42,42.0000,4.0,2.0,All-Wheel Drive,82,SIDI & PFI; Hybrid,8,1300,Regular Gasoline,8,38,TYX,Y,NaN,Automatic (AV-S6),66.7500,57.6664,0,0,0,0,0,0,SUVs,0,7.0,NaN,NaN,NaN,NaN

In [56]:
cars = cars[cars['year'] < 2021]
cars = cars[cars['avg_price'] <= 80000]
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score,lat,long,state,avg_price
0,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.080000,-80.440000,Florida,15990.0
1,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.770000,-80.200000,Florida,15990.0
2,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,27.588500,-80.392300,Florida,13900.0
3,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.549966,-81.391525,Florida,6500.0
4,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.610096,-81.298342,Florida,12900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936674,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Montana,54995.0
936675,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Wyoming,54995.0
936676,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.960000,-89.640000,Wisconsin,71590.0
936677,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,48.077990,-123.159590,Washington,55990.0
936678,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,61.138100,-149.867270,Alaska,28888.0

In [57]:
print(cars['avg_price'].dtype)

float64

In [58]:
cars['avg_price'] = pd.to_numeric(cars['avg_price'], errors='coerce')

In [59]:
cars['avg_price'] = cars['avg_price'].round()

In [60]:
cars.isna().sum()

id                     0
make                   0
model                  0
baseModel              0
year                   0
createdOn              0
modifiedOn             0
youSaveSpend           0
barrels08              0
city08                 0
co2                    0
co2TailpipeGpm         0
comb08                 0
comb08U                0
cylinders              0
displ                  0
drive                  0
engId                  0
eng_dscr          300589
feScore                0
fuelCost08             0
fuelType1              0
ghgScore               0
highway08              0
mfrCode                0
mpgData                0
trans_dscr        933399
trany                  0
UCity                  0
UHighway               0
hlv                    0
hpv                    0
lv2                    0
lv4                    0
pv2                    0
pv4                    0
VClass                 0
range                  0
score               1943
lat                    0
long                   0
state                  0
avg_price              0
dtype: int64

In [61]:
cars.dropna(subset = ['score'], inplace = True)

In [62]:
cars.isna().sum()

id                     0
make                   0
model                  0
baseModel              0
year                   0
createdOn              0
modifiedOn             0
youSaveSpend           0
barrels08              0
city08                 0
co2                    0
co2TailpipeGpm         0
comb08                 0
comb08U                0
cylinders              0
displ                  0
drive                  0
engId                  0
eng_dscr          299826
feScore                0
fuelCost08             0
fuelType1              0
ghgScore               0
highway08              0
mfrCode                0
mpgData                0
trans_dscr        931456
trany                  0
UCity                  0
UHighway               0
hlv                    0
hpv                    0
lv2                    0
lv4                    0
pv2                    0
pv4                    0
VClass                 0
range                  0
score                  0
lat                    0
long                   0
state                  0
avg_price              0
dtype: int64

In [63]:
cars = cars[cars['cylinders'] < 10]
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score,lat,long,state,avg_price
0,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.080000,-80.440000,Florida,15990.0
1,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.770000,-80.200000,Florida,15990.0
2,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,27.588500,-80.392300,Florida,13900.0
3,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.549966,-81.391525,Florida,6500.0
4,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.610096,-81.298342,Florida,12900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936674,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Montana,54995.0
936675,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Wyoming,54995.0
936676,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.960000,-89.640000,Wisconsin,71590.0
936677,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,48.077990,-123.159590,Washington,55990.0
936678,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,61.138100,-149.867270,Alaska,28888.0

In [64]:
cars = cars.reset_index(drop = True)
cars

,id,make,model,baseModel,year,createdOn,modifiedOn,youSaveSpend,barrels08,city08,co2,co2TailpipeGpm,comb08,comb08U,cylinders,displ,drive,engId,eng_dscr,feScore,fuelCost08,fuelType1,ghgScore,highway08,mfrCode,mpgData,trans_dscr,trany,UCity,UHighway,hlv,hpv,lv2,lv4,pv2,pv4,VClass,range,score,lat,long,state,avg_price
0,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.080000,-80.440000,Florida,15990.0
1,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,25.770000,-80.200000,Florida,15990.0
2,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,27.588500,-80.392300,Florida,13900.0
3,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.549966,-81.391525,Florida,6500.0
4,33399,Mazda,6,6,2014,Tue Jan 01 00:00:00 EST 2013,Mon Sep 26 00:00:00 EDT 2016,250,10.258966,25,305,305.0,29,29.0523,4.0,2.5,Front-Wheel Drive,6,SIDI,7,1850,Regular Gasoline,7,36,TKX,Y,NaN,Manual 6-spd,32.4042,52.7451,0,0,0,15,0,100,Midsize Sedans,0,9.0,28.610096,-81.298342,Florida,12900.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
929545,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Montana,54995.0
929546,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.354923,-106.680384,Wyoming,54995.0
929547,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,44.960000,-89.640000,Wisconsin,71590.0
929548,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,48.077990,-123.159590,Washington,55990.0
929549,42756,Mercedes-Benz,GLC350e 4matic,GLC-Class,2020,Wed Jun 24 00:00:00 EDT 2020,Fri Mar 25 00:00:00 EDT 2022,0,6.122730,23,176,176.0,25,25.0374,4.0,2.0,4-Wheel Drive,252,SIDI; PHEV,8,2700,Premium Gasoline,10,28,MBX,N,NaN,Automatic 9-spd,31.9000,39.8000,0,0,0,0,0,0,SUVs,0,5.0,61.138100,-149.867270,Alaska,28888.0

In [65]:
cars.to_csv('cars.csv', index = False)